### ISSUE TITLE
Não há opções de pagamento disponíveis

### ISSUE THREAD

**Issue by antthonycanuto** [Marjoel/pagseguro-opencart#12]
Detalhes do pagamento: Atenção: Não há opções de pagamento disponíveis. Entre em contato e informe os detalhes do pedido!

Não está aparecendo. Como faz pra resolver?

**Comment by ghost** [comment]
No meu caso eu alterei o idioma para português e a moeda para Real, apareceu a opção.

**Comment by morturus** [comment]
O mesmo acontece aqui, alguma solução?
