### ISSUE TITLE
Não abre a página para pagamento

### ISSUE THREAD

**Issue by liiverodrigues** [Marjoel/pagseguro-opencart#13]
Bom dia, estou com alguns problemas na versão 2.3.0.2 do opencart mesmo com tudo configurado no último passo da compra(Resumo do pedido) ele apenas fica carregando e não abre nada relacionado ao pagseguro para o cliente efetuar o pagamento.

![sem titulo](https://user-images.githubusercontent.com/19478412/28924124-fc14e238-7836-11e7-9b58-dda060dd6afe.png)

**Comment by guinadf** [comment]
Estou tendo o mesmo problema.  :/

**Comment by Diuliano-Oliveira** [comment]
estou com o mesmo problema, conseguiram resolver ?

**Comment by vagkaefer** [comment]
Mesmo problema aqui, algumas vezes aparece corretamente, outras vezes fica como na imagem, o belo "Carregando". A página web não mostra nenhum erro no console e no servidor não consegui encontrar nenhum erro que possa ajudar a desvendar o problema -.-

**Comment by liiverodrigues** [comment]
O elemento está com display:none; no botão do pagseguro... apenas removi isso e voltou a funcionar normalmente.
