### ISSUE TITLE
Nao carrega a página

### ISSUE THREAD

**Issue by zagalux** [Marjoel/pagseguro-opencart#2]
Estou usando o modulo do lightbox porém ele não carrega o pagseguro quando clico em pagar.

 loja micronos.com.br

**Comment by Marjoel** [comment]
Opa @zagalux, tudo bem?

Qual versão do Opencart você está utilizando?

Farei uma análise e já darei um retorno.

**Comment by zagalux** [comment]
Opaa
Utilizo a mais recente. Eu desinstalei o módulo mas vou reinstalar!

Att

Em 28 de mar de 2017 19:38, "Marjoel Moreira" <notifications@github.com>
escreveu:

**Comment by Marjoel** [comment]
Acabei de descobrir o problema e já solucionei, vou gerar uma nova versão e te aviso :)

**Comment by zagalux** [comment]
Ok, muito obrigado, agradeço pela atenção e dedicação! Parabéns pelo módulo!!! o próprio pagseguro nao desenvolveu para a versão mais recente...

**Comment by zagalux** [comment]
Baixei do 0 porém ainda fala q nao foi possivel exibir a pagina =(
Ops! Houve um problema e não foi possível exibir a página
no console do navegador ele retorna o seguinte:

http://micronos.com.br/index.php?route=extension/payment/pagseguro/order Failed to load resource: the server responded with a status of 404 (Not Found)
lightbox.html Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by zagalux** [comment]
Testei novamente e agora parece resolvido! acho q meu oc tinha dado algum bug! muito obrigado!

**Comment by zagalux** [comment]
o estranho é que precisa fazer a compra 2 vezes para funcionar, na primeira ela trava e na segunda funciona. entao chegam 2 pedidos para o admin e cliente

**Comment by Marjoel** [comment]
Descobri outro problema que poderia causar isso, resolvi e estou gerando uma nova versão, se puder testar por favor.
