### ISSUE TITLE
Precisa fazer a compra 2 vezes

### ISSUE THREAD

**Issue by zagalux** [Marjoel/pagseguro-opencart#3]
O cliente precisa fazer a compra duas vezes para funcionar, no primeiro ele nao conecta e no segundo da certo, precisando passar pelos parametros de finalização do pedido 2 x. Tem alguma configuração para alterar esse erro?

**Comment by Marjoel** [comment]
Opa!
Você pode me passar mais algumas informações do problema?

- Qual a versão do Opencart você está usando?
- Instalação limpa ou personalizada? 
- Havia outra instalação de outro módulo do PagSeguro?
- As credenciais do PagSeguro (e-mail e token) estão configuradas no módulo corretamente?
- A url do Opencart está configurada corretamente no PagSeguro?
- O teste está sendo feito via checkout mesmo ou você está realizando via postman ou alguma outra ferramenta semelhante? 

Abs,
Marjoel Moreira.

**Comment by zagalux** [comment]
Bom dia,

 
Qual a versão do Opencart você está usando? : 2.3.0.2
Instalação limpa ou personalizada? Instalação Limpa
Havia outra instalação de outro módulo do PagSeguro? Não, eu deletei todos os arquivos do PG e instalei os novos
As credenciais do PagSeguro (e-mail e token) estão configuradas no módulo corretamente? Sim
A url do Opencart está configurada corretamente no PagSeguro? Qual url?
O teste está sendo feito via checkout mesmo ou você está realizando via postman ou alguma outra ferramenta semelhante? Via checkout.

 O problema apresentado é que:
 Quando o cliente vai fazer a compra ele clica em pagar porém retorna o erro 500, e não carrega a página, porém quando retorna ao checkout e ele clica em pagar pela segunda vez, o pagamento é processado normalmente e a pagina do pagseguro é carregada corretamente e ele pode pagar o produto.

página- micronos.com.br

abs

**Comment by Marjoel** [comment]
Você pode me passar os dados da loja pra eu fazer um teste? Não consegui simular este erro.

Eu resolvi um problema na nova versão que eu acabei de gerar, você pode testar e ver se ocorre com essa nova versão?

Os dados você pode me mandar via facebook (https://www.facebook.com/MarjoelM) ou por e-mail (você vai encontrar meu e-mail em https://www.marjoel.com).

**Comment by rafaelsgritti** [comment]
O problema de fato foi resolvido, muito obrigado, agora funcionou de primeira!

 Valeu!!
